export const PATIENT_ENTERED = 'PATIENT_ENTERED';
export const FLIP_BODY = 'FLIP_BODY';
export const MUSCLE_SELECTED = 'MUSCLE_SELECTED';
export const MUSCLE_FORCE_CHANGED = 'MUSCLE_FORCE_CHANGED';
export const PRINTING_TOOGLE = "PRINTING_TOOGLE";
export const PAGE_LOADED = "PAGE_LOADED";
